### ISSUE TITLE
Detail issues: U03_Ex07

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#10]
[Chapter 3/U03_07_Distance.py](https://github.com/sebastians22/COOP2018/commit/9d518282103e573d54e2cd065345041894022d4a#diff-84c26d3f731d5abb12cb00266cce4f37)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Mark this issue resolved when you have fixed everything mentioned.

**Comment by sebastians22** [comment]
Fixed it
