### ISSUE TITLE
Unfinished: U03_Ex15

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#12]
[Chapter 3/U03_Ex15_pi.py](https://github.com/sebastians22/COOP2018/commit/9d518282103e573d54e2cd065345041894022d4a#diff-ad5f1efbe668e3b10fa496f10a7ef385)

In the absence of a README file, I looked at this program. It is unfinished.

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Mark this issue resolved when you have fixed everything mentioned.

**Comment by bmontana-edu** [comment]
Please address these issues ASAP!

**Comment by sebastians22** [comment]
Fixed it
