### ISSUE TITLE
Multiple Issues: U03_Ex09

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#13]
[Chapter 3/U03_Ex09_Formula_For_Triangle.py](https://github.com/sebastians22/COOP2018/commit/9d518282103e573d54e2cd065345041894022d4a#diff-cbbe35a90f981222a049bb37629b432a)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Close this issue when you have fixed everything mentioned.

**Comment by sebastians22** [comment]
Fixed it
