### ISSUE TITLE
Incorrect Output: U02_Ex09

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#14]
[Chaper02/U02_Ex09_ConvertFtoC.py](https://github.com/sebastians22/COOP2018/commit/06624ae6b4684af7f0cf700792a2be8eef0bbe7b#diff-546d48b673b6c809dc72e795d0fccde3)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.
Close this issue when you have fixed everything mentioned.

**Comment by sebastians22** [comment]
Fixed it
