### ISSUE TITLE
Algorithm issue: U03_Ex06

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#19]
[Chapter 3/U03_Ex06_Slope.py](https://github.com/sebastians22/COOP2018/commit/501938882c597f83acb3ace0566e00393525aa8a#diff-47ab068e6340a51da542194f8381a283)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Close this issue when you have fixed everything mentioned.

**Comment by sebastians22** [comment]
I added more to the algorithm
