### ISSUE TITLE
Program requirements not met

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#2]
[Chaper02/U02_Ex05_TableCandF.py](https://github.com/sebastians22/COOP2018/commit/0668804046a7793526c0e15f0ca41c6caba6b928#diff-5324df63932d0fb64f8558ff7bfbec96)

Please reply to comments and mark this issue resolved after fixing issue(s).
@sebastians22

**Comment by sebastians22** [comment]
I fixed and replied to all of your comments
