### ISSUE TITLE
Detail needed: U04_Ex02

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#23]
[Chapter 4/U04_Ex02_Target.py](https://github.com/sebastians22/COOP2018/commit/aae9296d281a8d95c79e1dbd7197fb6d69286150#diff-162fb2cdee633546ce837b8371f6a811)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Close this issue when you have fixed everything mentioned.

**Comment by sebastians22** [comment]
Fixed it
