### ISSUE TITLE
Readability issue: U04_03

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#24]
[Chapter 4/U04_03_Face.py](https://github.com/sebastians22/COOP2018/commit/aae9296d281a8d95c79e1dbd7197fb6d69286150#diff-c4ae9c5268c10961a12e096e936e9f36)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Close this issue when you have fixed everything mentioned.

**Comment by sebastians22** [comment]
Fixed it
