### ISSUE TITLE
Detail issues: U03_Ex06

### ISSUE THREAD

**Issue by bmontana-edu** [sebastians22/COOP2018#9]
[Chapter 3/U03_Ex06_Slope.py](https://github.com/sebastians22/COOP2018/commit/9d518282103e573d54e2cd065345041894022d4a#diff-47ab068e6340a51da542194f8381a283)

Please address every comment I have made to your programs. Reply to each comment so I will know you fixed the issues.

Close this issue when you have fixed everything mentioned.

**Comment by bmontana-edu** [comment]
Please resolve this issue ASAP!

**Comment by sebastians22** [comment]
I fixed all the

**Comment by sebastians22** [comment]
issues and I replied to all of the comments
